import torch
x=torch.arange(12,dtype=torch.float32).reshape((3,4))
y=torch.ones((3,4))
print(x+1)
print(x*2)
print(x**2)
print(x@y.T)
print(torch.cat((x,y),dim=0))
print(torch.cat((x,y),dim=1))
print(x==y)
x1=torch.tensor([1,2])
y1=torch.tensor( [[1],[2],[3]])
print(x1+y1)
print(x1*y1)
print(x.T)
print(x[0:2,1:3])
test=torch.randn(2,4)*5
print(test)
#动手
a=torch.arange(6).reshape(2,3)
b=torch.arange(1,25,2).reshape(3,4)
print(b)
print(a@b)
print(x.dtype,a.dtype,x.shape,a.device)